# useEffect: HTTP requests

## Background

HTTP requests are another common side-effect that we need to do in applications.
This is no different from the side-effects we need to apply to a rendered DOM or
when interacting with browser APIs like localStorage. In all these cases, we do
that within a `useEffect` hook callback. This hook allows us to ensure that
whenever certain changes take place, we apply the side-effects based on those
changes.

One important thing to note about the `useEffect` hook is that you cannot return
anything other than the cleanup function. This has interesting implications with
regard to async/await syntax:

```javascript
// this does not work, don't do this:
React.useEffect(async () => {
  const result = await doSomeAsyncThing()
  // do something with the result
})
```

The reason this doesn't work is because when you make a function async, it
automatically returns a promise (whether you're not returning anything at all,
or explicitly returning a function). This is due to the semantics of async/await
syntax. So if you want to use async/await, the best way to do that is like so:

```javascript
React.useEffect(() => {
  async function effect() {
    const result = await doSomeAsyncThing()
    // do something with the result
  }
  effect()
})
```

This ensures that you don't return anything but a cleanup function.

ðŸ¦‰ I find that it's typically just easier to extract all the async code into a
utility function which I call and then use the promise-based `.then` method
instead of using async/await syntax:

```javascript
React.useEffect(() => {
  doSomeAsyncThing().then(result => {
    // do something with the result
  })
})
```

But how you prefer to do this is totally up to you :)

## Exercise

Production deploys:

- [Exercise](https://react-hooks.netlify.app/isolated/exercise/06.js)
- [Final](https://react-hooks.netlify.app/isolated/final/06.js)

In this exercise, we'll be doing data fetching directly in a useEffect hook
callback within our component.

Here we have a form where users can enter the name of a pokemon and fetch data
about that pokemon. Your job will be to create a component which makes that
fetch request. When the user submits a pokemon name, our `PokemonInfo` component
will get re-rendered with the `pokemonName`

## Extra Credit

### 1. ðŸ’¯ handle errors

[Production deploy](https://react-hooks.netlify.app/isolated/final/06.extra-1.js)

Unfortunately, sometimes things go wrong and we need to handle errors when they
do so we can show the user useful information. Handle that error and render it
out like so:

```jsx
<div role="alert">
  There was an error: <pre style={{whiteSpace: 'normal'}}>{error.message}</pre>
</div>
```

You can make an error happen by typing an incorrect pokemon name into the input.

### 2. ðŸ’¯ use a status

[Production deploy](https://react-hooks.netlify.app/isolated/final/06.extra-2.js)

Our logic for what to show the user when is kind of convoluted and requires that
we be really careful about which state we set and when.

We could make things much simpler by having some state to set the explicit
status of our component. Our component can be in the following "states":

- `idle`: no request made yet
- `pending`: request started
- `resolved`: request successful
- `rejected`: request failed

Try to use a status state by setting it to these string values rather than
relying on existing state or booleans.

Learn more about this concept here:
https://kentcdodds.com/blog/stop-using-isloading-booleans

### 3. ðŸ’¯ store the state in an object

[Production deploy](https://react-hooks.netlify.app/isolated/final/06.extra-3.js)

You'll notice that we're calling a bunch of state updaters in a row. This is
normally not a problem, but each call to our state updater can result in a
re-render of our component. React normally batches these calls so you only get a
single re-render, but it's unable to do this in an asynchronous callback (like
our promise success and error handlers).

So you might notice that if you do this:

```javascript
setStatus('resolved')
setPokemon(pokemon)
```

You'll get an error indicating that you cannot read `image` of `null`. This is
because the `setStatus` call results in a re-render that happens before the
`setPokemon` happens.

In the future, you'll learn about how `useReducer` can solve this problem really
elegantly, but we can still accomplish this by storing our state as an object
that has all the properties of state we're managing.

See if you can figure out how to store all of your state in a single object with
a single `React.useState` call so I can update my state like this:

```javascript
setState({status: 'resolved', pokemon})
```

### 4. ðŸ’¯ create an ErrorBoundary component

[Production deploy](https://react-hooks.netlify.app/isolated/final/06.extra-4.js)

We've already solved the problem for errors in our request, we're only handling
that one error. But there are a lot of different kinds of errors that can
happen in our applications.

No matter how hard you try, eventually your app code just isnâ€™t going to behave
the way you expect it to and youâ€™ll need to handle those exceptions. If an error
is thrown and unhandled, your application will be removed from the page, leaving
the user with a blank screen... Kind of awkward...

Luckily for us, thereâ€™s a simple way to handle errors in your application using
a special kind of component called an
[Error Boundary](https://reactjs.org/docs/error-boundaries.html). Unfortunately,
there is currently no way to create an Error Boundary component with a function
and you have to use a class component instead.

In this extra credit, read up on ErrorBoundary components, and try to create one
that handles this and any other error for the `PokemonInfo` component.

ðŸ’° to make your error boundary component handle errors from the `PokemonInfo`
component, instead of rendering the error within the `PokemonInfo` component,
you'll need to `throw error` right in the function so React can hand that to the
error boundary. So `if (status === 'rejected') throw error`.

### 5. ðŸ’¯ re-mount the error boundary

[Production deploy](https://react-hooks.netlify.app/isolated/final/06.extra-5.js)

You might notice that with the changes we've added, we now cannot recover from
an error. For example:

1. Type an incorrect pokemon
2. Notice the error
3. Type a correct pokemon
4. Notice it doesn't show that new pokemon's information (even though the
   network request did work).

The reason this is happening is because the `error` that's stored in the
internal state of the `ErrorBoundary` component isn't getting reset, so it's not
rendering the `children` we're passing to it.

So what we need to do is reset the ErrorBoundary's `error` state to `null` so it
will re-render. But how do we access the internal state of our `ErrorBoundary`
to reset it? Well, there are a few ways we could do this by modifying the
`ErrorBoundary`, but one thing you can do when you want to _reset_ the state of
a component, is by providing it a `key` prop which can be used to unmount and
re-mount a component.

The `key` you can use? Try the `pokemonName`!

### 6. ðŸ’¯ use react-error-boundary

[Production deploy](https://react-hooks.netlify.app/isolated/final/06.extra-6.js)

As cool as our own `ErrorBoundary` is, I'd rather not have to maintain it in the
long-term. Luckily for us, there's an npm package we can use instead and it's
already installed into this project. It's called
[`react-error-boundary`](https://github.com/bvaughn/react-error-boundary).

Go ahead and give that a look and swap out our own `ErrorBoundary` for the one
from `react-error-boundary`.

### 7. ðŸ’¯ reset the error boundary

[Production deploy](https://react-hooks.netlify.app/isolated/final/06.extra-7.js)

You may have noticed a problem with the way we're resetting the internal state
of the `ErrorBoundary` using the `key`. Unfortunately, we're not only
re-mounting the `ErrorBoundary`, we're also re-mounting the `PokemonInfo` which
results in a flash of the initial "Submit a pokemon" state whenever we change
our pokemon.

So let's backtrack on that and instead we'll use `react-error-boundary`'s
`resetErrorBoundary` function (which will be passed to our `ErrorFallback`
component) to reset the state of the `ErrorBoundary` when the user clicks a "try
again" button.

> ðŸ’° feel free to open up the finished version by clicking the link in the app
> so you can get an idea of how this is supposed to work.

Once you have this button wired up, we need to react to this reset of the
`ErrorBoundary`'s state by resetting our own state so we don't wind up
triggering the error again. To do this we can use the `onReset` prop of the
`ErrorBoundary`. In that function we can simply `setPokemonName` to an empty
string.

### 8. ðŸ’¯ use resetKeys

[Production deploy](https://react-hooks.netlify.app/isolated/final/06.extra-8.js)

Unfortunately now the user can't simply select a new pokemon and continue with
their day. They have to first click "Try again" and then select their new
pokemon. I think it would be cooler if they can just submit a new `pokemonName`
and the `ErrorBoundary` would reset itself automatically.

Luckily for us `react-error-boundary` supports this with the `resetKeys` prop.
You pass an array of values to `resetKeys` and if the `ErrorBoundary` is in an
error state and any of those values change, it will reset the error boundary.

ðŸ’° Your `resetKeys` prop should be: `[pokemonName]`

## ðŸ¦‰ Elaboration and Feedback

<div>
<span>After the instruction, if you want to remember what you've just learned, then </span>
<a rel="noopener noreferrer" target="_blank" href="https://ws.kcd.im/?ws=React%20Hooks%20%F0%9F%8E%A3&e=06%3A%20useEffect%3A%20HTTP%20requests&em=">
  fill out the elaboration and feedback form.
</a>
</div>
